---
- import_tasks: all_in_one.yml
  when: bbb_monitoring_all_in_one_enable | bool or bbb_monitoring_external | bool

- import_tasks: systemd.yml
  when: bbb_monitoring_systemd_enable | bool

- name: Copy monitoring nginx configuration file
  template:
    src: "monitoring/monitoring.nginx.j2"
    dest: "/etc/bigbluebutton/nginx/monitoring.nginx"
    mode: '0644'
  notify:
    - reload nginx

- name: Generate htpasswd file for external access if enabled
  htpasswd:
    path: "/etc/bigbluebutton/nginx/.htpasswd"
    name: "{{ bbb_monitoring_htpasswd_user }}"
    password: "{{ bbb_monitoring_htpasswd }}"
    owner: root
    group: root
    mode: 0644
  no_log: true
  when: bbb_monitoring_external | bool and bbb_monitoring_htpasswd_user is defined and bbb_monitoring_htpasswd is defined
  notify:
    - reload nginx
