---
- name: "Update config for proxy mode"
  when: "bbb_cluster_proxy is defined"
  ansible.builtin.set_fact:
    bbb_config_web_base: |
      {{bbb_config_web_base | combine({
        "defaultHTML5ClientUrl": "https://"+bbb_cluster_proxy+"/"+bbb_cluster_node+"/html5client",
        "presentationBaseURL": "https://"+bbb_hostname+"/bigbluebutton/presentation",
        "accessControlAllowOrigin": "https://"+bbb_cluster_proxy,
        "graphqlWebsocketUrl": "wss://"+bbb_hostname+"/graphql",
        "graphqlApiUrl": "https://"+bbb_hostname+"/api/rest"
      })}}
    bbb_config_html5_base: |
      {{bbb_config_html5_base | combine({
        'public': {
          'app': {
            'basename': "/"+bbb_cluster_node+"/html5client",
            'bbbWebBase': 'https://'+bbb_hostname+'/bigbluebutton',
            'learningDashboardBase': 'https://'+bbb_hostname+'/learning-analytics-dashboard',
            'userSettingsStorage': 'local',
          },
          'media': {
            'stunTurnServersFetchAddress': 'https://'+bbb_hostname+'/bigbluebutton/api/stuns',
            'sip_ws_host': bbb_hostname
          },
          'kurento': {
            'wsUrl': 'wss://'+bbb_hostname+'/bbb-webrtc-sfu'
          },
          'presentation': {
            'uploadEndpoint': 'https://'+bbb_hostname+'/bigbluebutton/presentation/upload'
          },
          'pads': {
            'url': 'https://'+bbb_hostname+'/pad'
          }
        }
      }, recursive=True)}}
