---
- name: Install chrony
  apt:
    name: chrony
    state: present
  when: bbb_ntp_cron

- name: Check if chrony is installed
  package_facts:
    manager: apt

- name: Get the list of services
  service_facts:
- name: Disable/enable chrony service
  service:
    name: chrony
    enabled: "{{ bbb_ntp_cron | ternary('false', 'true') }}"
    state: "{{ bbb_ntp_cron | ternary('stopped', 'started') }}"
  when: "'chrony' in ansible_facts.packages"

# on Ubuntu 18.04 timedatectl set-ntp just controls systemd-timesynd, so this is an idempotent alternative
- name: Disable/enable systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: "{{ (bbb_ntp_cron | bool or 'chrony' in ansible_facts.packages) | ternary('false', 'true') }}"
    state: "{{ (bbb_ntp_cron | bool or 'chrony' in ansible_facts.packages) | ternary('stopped', 'started') }}"
  when: "'systemd-timesyncd.service' in services and services['systemd-timesyncd.service'].status not in ['not-found','masked']"

- name: Add/remove time syncronisation cronjob
  cron:
    name: sync system time
    job: chronyd -q
    state: "{{ bbb_ntp_cron | ternary('present', 'absent') }}"
    day: "{{ bbb_ntp_cron_day }}"
    hour: "{{ bbb_ntp_cron_hour }}"
    minute: "{{ bbb_ntp_cron_minute }}"
