- name: Install nfs-common
  apt:
    name:
      - nfs-common
    state: latest
  when: bbb_recordings_nfs['enable'] and not bbb_disable_recordings

- name: Ensure group "scalelite-spool" exists
  group:
    gid: 2000
    name: scalelite-spool
    state: present

- name: adding existing user bigbluebutton to group scalelite-spool
  user:
    name: 'bigbluebutton'
    groups:
      - 'scalelite-spool'
    append: yes

- name: Create scalelite tmp-dir
  file:
    path: /mnt/scalelite-recordings/var/bigbluebutton
    state: directory
    mode: 0755
    owner: bigbluebutton
    group: bigbluebutton

- name: set mountpoints
  mount:
    path: /mnt/scalelite-recordings/var/bigbluebutton/
    src: "{{ bbb_recordings_nfs['path'] }}"
    fstype: nfs
    opts: rw,nfsvers=3,sec=sys,hard,proto=tcp
    passno: '2'
    state: mounted

- name: Install scalelite.yml
  template:
    src: 'recordings/scalelite.yml'
    dest: /usr/local/bigbluebutton/core/scripts
    owner: root
    group: root
    force: true
    mode: '0755'

- name: Install scalelite_post_publish.rb
  template:
    src: 'recordings/scalelite_post_publish.rb'
    dest: /usr/local/bigbluebutton/core/scripts/post_publish
    owner: root
    group: root
    force: true
    mode: '0755'
